name: "Docs redirect check"

on:
  pull_request:
    paths: [docs/**]

permissions:
  contents: read

jobs:
  redirect-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Needed to fetch the target branch
          fetch-depth: 0
          persist-credentials: false
      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      - name: "Check docs redirects"
        run: nix run --print-build-logs '.#ci-scripts/docs-redirect-check'
