name: "Docs linkcheck"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'  # At 07:00 on Monday

permissions:
  contents: read

concurrency:
  group: "docs-linkcheck"
  cancel-in-progress: true

jobs:
  linkcheck:
    if: "github.repository_owner == 'epics-extensions'"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      - name: "Check docs links"
        run: nix run --print-build-logs '.#ci-scripts/docs-linkcheck'
